### PR TITLE
Speed up downloads by creating parallel download requests.

### PR DESCRIPTION
**Pull request by ericandrewlewis**
Utilizing multiple processes for `wget` calls speeds downloads up by about 12x.

Slurping the entire plugins directory took me just over an hour with this change. Your ~~mileage~~bandwidth may vary.

### CODE REVIEW

**Comment by iandunn** [comment]
+1, this worked well for me. Took 91 minutes to grab everything from scratch.

**Comment by nylen** [comment]
@ericandrewlewis this worked well for me but it needs better progress reporting and error handling.  maybe something like this?

- create a separate `./download` script that downloads a single plugin and reports progress
- check the result of the main `exec` - on both OS X and Linux, `xargs` will exit with a non-zero code if one of its commands fails

**Comment by ericandrewlewis** [comment]
👋 @nylen Better progress reporting and error handling would be good. What you suggest makes sense to perhaps parallelize individual download processes to track if one goes bad.

**Comment by nylen** [comment]
@ericandrewlewis If you are available to work on it further, I'd be happy to review :)

**Comment by ericandrewlewis** [comment]
Sorry I won't be working on this further, thanks for the offer to review though 🙂

**Pull request closed without merging**
