### PR TITLE
Rewrite to add batch downloading and auto-resuming

### LINKED ISSUE #9: PHP Warning, Not Updating
Hey Mark,

Thanks for this code!

My initial _slurp_ went just fine, but I just tried to run an update several times and am not sure what's wrong.  I'm using the latest code from the git repo.

Here's what I get when updating:

> [eric@ea-fedora WordPress-Plugin-Directory-Slurper]$ sudo ./update
> Determining most recent SVN revision...
> Most recent SVN revision: 725464
> Last synced revision: 678503
> PHP Warning:  file_get_contents(http://plugins.trac.wordpress.org/log/?
> verbose=on&mode=follow_copy&format=changelog&rev=725464&limit=46961): failed to > open stream: HTTP request failed!  in /home/eric/Dropbox/dev/vhost/WordPress-Plugin-
> Directory-Slurper/update on line 57
> [CLEANUP] Updated plugins/.last-revision to 725464
> [SUCCESS] Done updating plugins!
> It took 1 minutes and 23 seconds to update 0 plugins
> [DONE]

It's probably been about two months since the original _slurp_, which went flawlessly and I have never yet updated (or tried).

### LINKED ISSUE #20: Question about multi-threaded capabilities for this slurper
I noticed https://github.com/krakjoe/pthreads exists

Does it seem feasible to perhaps adjust that php library to slurp all the plugins more quickly?

### PR DESCRIPTION
**Pull request by nylen**
This PR has several new features and improvements:

- Download 12 plugins at a time in parallel, using `xargs` and a separate `./download` script that downloads a single plugin in a new process.  Fixes #20 and closes #12.
- Fetch plugins repo changelogs <s>in batches of 2500 revisions at a time</s> using a `svn log` command instead of downloading changelogs from Trac.  This is much faster than the previous method, is probably nicer to the .org servers, and does not fail when updating an older repository with lots of changes.  Fixes #9.
- During an update run, track the current SVN revision of our copy of the plugins repository.  This is a bit complicated because a given plugin can be updated in several revisions, and we want to avoid downloading the same zip file multiple times, but it closes #14.
- Better progress output.

### CODE REVIEW

**Comment by codebykat** [comment]
Tested this on OSX and it works well for both a fresh start and partial update. 👍

**Comment by iandunn** [comment]
It looks like it's updating the `Last synced revision` even if the sync fails:

```
> ./update 
Determining most recent SVN revision...
Most recent SVN revision : 1698320
Last synced revision     : 1698313
Requesting plugins changelog:
svn log -v -q https://plugins.svn.wordpress.org/ -r 1698320:1698314
at r1698320
5 plugins to update (7 SVN revisions)
sh: wget: command not found
sh: wget: command not found
sh: wget: command not found
sh: wget: command not found
sh: wget: command not found
[FAIL]  20.0%  wise-forms
[FAIL]  40.0%  easy-facebook-likebox
[FAIL]  60.0%  appmaker-woocommerce-mobile-app-manager
[FAIL]  80.0%  probuilder  (local copy now at r1698318)
[FAIL] 100.0%  cs-cart-to-woocommerce-migration  (local copy now at r1698320)
[SUCCESS] Done updating plugins!
It took 0 minutes and 1 second to update 0 plugins (5 failed).
[DONE]

> brew install wget
[succesfully installed]

> ./update 
Determining most recent SVN revision...
Most recent SVN revision : 1698321
Last synced revision     : 1698320
Requesting plugins changelog:
svn log -v -q https://plugins.svn.wordpress.org/ -r 1698321:1698321
at r1698321
1 plugin to update (1 SVN revision)
[ OK ] 100.0%  woo-shipping-additional-days
[SUCCESS] Done updating plugins!
It took 0 minutes and 2 seconds to update 1 plugin (0 failed).
[DONE]
```

I expected the 5 plugins from the first `update` to be installed, along with `woo-shipping-additional-days`.

**Comment by nylen** [comment]
Good catch @iandunn.  We need to differentiate between the different types of errors that `wget` can return - 404 errors are expected for plugins that have been removed from the directory, but network errors or failure to launch `wget` should not count as a successful download.

This is fixed in 58c6475.  To test:

- change line 63 of `download` from `wget` to `xwget` or some other command that doesn't exist
- `echo 1698313 > plugins/.last-revision`
- `./update` - this should fail without updating the revision
- undo your change to `./download` and run `./update` again

**Comment by nylen** [comment]
I think this is OK to ship.  Please let me know if I broke anything :)

**Comment by iandunn** [comment]
Yup, that fixed it :)

**Pull request merged**
